version: '3'
services:
    api:
        build: .
        ports:
            - "3000:3000"
        command: npm run dev
        volumes:
            - .:/usr/src/app
        environment:
            DB_HOST: 'api-postgres-1'
            DB_PORT: 5432
            DB_USER: 'postgres'
            DB_PASSWORD: 'postgres'
            DB_NAME: 'postgres'
            ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET
            REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET
            ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE
            REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE
    postgres:
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:

